title: PROBE
email: your-team@example.com
description: >- 
  Poisson-Regressed Observations of Big-Six Evolution in Premier League.
  Interactive dashboard for Premier League data analysis and prediction.

baseurl: ""
url: ""

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing (REMOVED model/ from here)
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - requirements.txt
  - "*.py"

# Include additional directories
include:
  - model/
  - docs/

# Keep files during regeneration  
keep_files:
  - model/
